[variables]
NODE_VERSION = "20.19.0"
NPM_CONFIG_PRODUCTION = "false"

[phases.build]
cmds = [
  "npm ci --production=false",
  "npm run build"
]

[phases.start]
cmd = "npm start"

[static]
dir = "dist" 